#!/usr/bin/env python3

from quarters.master.jobfetcher import JobFetcher

import quarters.config

from quarters.state import State

from quarters.spout import start_master_web

from quarters.master.statuspoller import StatusPoller

if __name__ == '__main__':
    local_state = State()

    config = quarters.config.read_config('conf/quarters.conf')
    print( config )

    jf = JobFetcher( local_state, config )
    jf.start()

    # list of ips, ports of those ips
    sp = StatusPoller( local_state, config )
    sp.start()

    # get it up!
    start_master_web( local_state, config )
