#!/usr/bin/env python3

#from quarters.builder.jobmanager import JobOverlord, JobDescription

import quarters.config

#import time

#from multiprocessing import Manager

#from quarters.builder.spout import Spout

if __name__ == '__main__':
    #manager = Manager()
    #job_states = manager.dict()

    config = quarters.config.read_master('conf/master.conf')
    print( config )

    # set maximum number of simultaneous chroots
    #jo = JobOverlord( job_states, config )
    #jo.start()

    # get it up!
    #webserver = Spout( job_states )
    #webserver.start()
