#!/usr/bin/env python3

from quarters.master.jobmanager import JobFetcher

import quarters.config

from multiprocessing import Manager

from quarters.master.spout import Spout

if __name__ == '__main__':
    manager = Manager()
    job_states = manager.dict()

    pending_jobs = manager.Queue()

    config = quarters.config.read_master('conf/master.conf')
    print( config )

    # set maximum number of simultaneous chroots
    jf = JobFetcher( job_states, pending_jobs, config )
    jf.start()

    # get it up!
    webserver = Spout( job_states )
    webserver.start()
