#!/usr/bin/env python3

from quarters.builder.jobmanager import JobOverlord, JobDescription

import quarters.config

if __name__ == '__main__':
    config = quarters.config.read('conf/builder.conf')

    jo = JobOverlord( 5 )
    jo.start()

    # add jobs
    for i in range( 100 ):
        # job description: ujid, pkgname, pkgsrc
        jd = JobDescription( str( i ), str( i ), 'https://aur.archlinux.org/packages/rr62x/rr62x.tar.gz' )
        jo.add_job( jd )
