#!/usr/bin/env python3

from quarters.builder.jobmanager import JobOverlord, JobDescription

import quarters.config

import time

from multiprocessing import Manager

from quarters.builder.spout import Spout

if __name__ == '__main__':
    manager = Manager()
    job_states = manager.dict()

    config = quarters.config.read_builder('conf/builder.conf')
    print( config )

    # set maximum number of simultaneous chroots
    #jo = JobOverlord( config['chroots'] )
    jo = JobOverlord( 2, job_states )
    jo.start()

    pkgname = 'libuser'
    pkgurl = 'https://aur.archlinux.org/packages/' + pkgname + '/' + pkgname + '.tar.gz'

    # job description: ujid, pkgname, pkgsrc
    jd = JobDescription( '0', pkgname, pkgurl )
    jo.add_job( jd )

    time.sleep( 2 )
    jd = JobDescription( '1', pkgname, pkgurl )

    jo.add_job( jd )

    # get it up!
    webserver = Spout( job_states )
    webserver.start()
