#!/usr/bin/env python3

import quarters
import quarters.utils

def main():
    '''
    The main funtion for the builder
    '''
    master = quarters.Builder()
    # Try to make this not run as root
    #quarters.utils.check_root()
    master.start_builder_server()

if __name__ == '__main__':
    main()
