#!/usr/bin/env python3

import quarters
import quarters.utils

def main():
    '''
    The main funtion for the master server
    '''
    master = quarters.Master()
    # Lets try to make this be able to run as a user
    #quarters.utils.check_root()
    master.start_master_server()

if __name__ == '__main__':
    main()
