#!/usr/bin/env python3

import quarters
import quarters.utils

def main():
    '''
    The main funtion yo!
    '''
    master = quarters.Master()
    quarters.utils.check_root()
    master.start_master_server()

if __name__ == '__main__':
    main()
